### ISSUE TITLE
Download Unauthorized

### ISSUE THREAD

**Issue by rokkay** [code16/sharp#130]
Hi guys, im trying to download a uploaded file but i dont have permission. I defined the policies for this entity:

```php
namespace App\Sharp\Policies;

class EmpresaPolicy {
    public function entity()
    {
        return sharp_user()->hasRole('Administrador');
    }

    public function view()
    {
        return sharp_user()->hasRole('Administrador');
    }

    public function update()
    {
        return sharp_user()->hasRole('Administrador');
    }
    
    public function delete()
    {
        return sharp_user()->hasRole('Administrador');
    }

    public function create()
    {
        return sharp_user()->hasRole('Administrador');        
    }
}
```
All the other actions works well, but the download not. This is the log:

```log
[2019-04-26 09:28:57] local.ERROR: Unauthorized action {"exception":"[object] (Code16\\Sharp\\Exceptions\\Auth\\SharpAuthorizationException(code: 0): Unauthorized action at C:\\wamp64\\www\\bestture\\vendor\\code16\\sharp\\src\\Auth\\SharpAuthorizationManagerForEntities.php:110)
[stacktrace]
#0 C:\\wamp64\\www\\bestture\\vendor\\code16\\sharp\\src\\Auth\\SharpAuthorizationManagerForEntities.php(39): Code16\\Sharp\\Auth\\SharpAuthorizationManagerForEntities->deny()
#1 C:\\wamp64\\www\\bestture\\vendor\\code16\\sharp\\src\\Auth\\SharpAuthorizationManagerForEntities.php(19): Code16\\Sharp\\Auth\\SharpAuthorizationManagerForEntities->checkEntityLevelAuthorization('empresa')
#2 C:\\wamp64\\www\\bestture\\vendor\\code16\\sharp\\src\\Auth\\SharpAuthorizationManager.php(22): Code16\\Sharp\\Auth\\SharpAuthorizationManagerForEntities->checkForEntity('view', 'empresa', '2')
#3 C:\\wamp64\\www\\bestture\\vendor\\code16\\sharp\\src\\sharp_helper.php(85): Code16\\Sharp\\Auth\\SharpAuthorizationManager->check('view', 'empresa', '2')
#4 C:\\wamp64\\www\\bestture\\vendor\\code16\\sharp\\src\\Http\\Api\\FormDownloadController.php(33): sharp_check_ability('view', 'empresa', '2')
#5 [internal function]: Code16\\Sharp\\Http\\Api\\FormDownloadController->show('empresa', '2', 'seguro_accident...')
#6 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array(Array, Array)
#7 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('show', Array)
#8 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Code16\\Sharp\\Http\\Api\\FormDownloadController), 'show')
#9 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(176): Illuminate\\Routing\\Route->runController()
#10 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(682): Illuminate\\Routing\\Route->run()
#11 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 C:\\wamp64\\www\\bestture\\vendor\\code16\\sharp\\src\\Http\\Middleware\\Api\\SetSharpLocale.php(22): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Code16\\Sharp\\Http\\Middleware\\Api\\SetSharpLocale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 C:\\wamp64\\www\\bestture\\vendor\\code16\\sharp\\src\\Http\\Middleware\\Api\\BindSharpValidationResolver.php(22): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Code16\\Sharp\\Http\\Middleware\\Api\\BindSharpValidationResolver->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 C:\\wamp64\\www\\bestture\\vendor\\code16\\sharp\\src\\Http\\Middleware\\Api\\AddSharpContext.php(55): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Code16\\Sharp\\Http\\Middleware\\Api\\AddSharpContext->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 C:\\wamp64\\www\\bestture\\vendor\\code16\\sharp\\src\\Http\\Middleware\\Api\\HandleSharpApiErrors.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Code16\\Sharp\\Http\\Middleware\\Api\\HandleSharpApiErrors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#56 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#57 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#58 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#59 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#60 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#61 C:\\wamp64\\www\\bestture\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(65): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 C:\\wamp64\\www\\bestture\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#65 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#68 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#71 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#74 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#77 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#80 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#81 C:\\wamp64\\www\\bestture\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#82 C:\\wamp64\\www\\bestture\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#83 {main}
"}
```

Thanks in advance.

**Comment by dvlpp** [comment]
The only way I was able to reproduce this is by writing the `entity()` method of the `Policy` class like this:

```php
public function entity(User $user)
{
    return false;
}
```

Maybe for a reason I can't understand `sharp_user()` isn't returning the current user in your case (in which case it will still be an issue). Can you try to replace tour method with this one:

```php
public function entity($user)
{
    return $user->hasRole('Administrador');
}
```

Another thing: did you defined [global authorizations](https://github.com/code16/sharp/blob/master/docs/entity-authorizations.md#global-authorizations) for this entity?

**Comment by rokkay** [comment]
I replaced the code but still the problem. I tried to return true too but its the same. In this project im using a guard to access Sharp, but its defined in `config\sharp.php`
```php
    public function entity()
    {
        return true;
    }
```

Here's my configuration file, as you can see i have global authorization in other entities but not in this.
```php
return [
    "entities" => [
        "user" => [
            "list" => \App\Sharp\Users\UserSharpList::class,
            "form" => \App\Sharp\Users\UsersSharpForm::class,
            "validator" => \App\Sharp\Users\UserSharpValidator::class,
            "policy" => \App\Sharp\Policies\UserPolicy::class
        ],
        "empresa" => [
            "list" => \App\Sharp\Empresas\EmpresaSharpList::class,
            "form" => \App\Sharp\Empresas\EmpresaSharpForm::class,
            "validator" => \App\Sharp\Empresas\EmpresaSharpValidator::class,
            "policy" => \App\Sharp\Policies\EmpresaPolicy::class
        ],
        "actividad" => [
            "list" => \App\Sharp\Actividades\ActividadSharpList::class,
            "form" => \App\Sharp\Actividades\ActividadSharpForm::class,
            "validator" => \App\Sharp\Actividades\ActividadSharpValidator::class,
            "policy" => \App\Sharp\Policies\ActividadPolicy::class
        ],
        "categoria" => [
            "list" => \App\Sharp\Categorias\CategoriaSharpList::class,
            "form" => \App\Sharp\Categorias\CategoriaSharpForm::class,
            // "validator" => \App\Sharp\SpaceshipSharpValidator::class,
            "policy" => \App\Sharp\Policies\CategoriaPolicy::class
        ],
        "pago" => [
            "list" => \App\Sharp\Pagos\PagoSharpList::class,
            "form" => \App\Sharp\Pagos\PagoSharpForm::class,
            "policy" => \App\Sharp\Policies\PagoPolicy::class,
            "authorizations" => [
                "delete" => false,
                "create" => false,
                "update" => false
            ]
        ],
        "reserva" => [
            "list" => \App\Sharp\Reservas\ReservaSharpList::class,
            "form" => \App\Sharp\Reservas\ReservaSharpForm::class,
           // "validator" => \App\Sharp\Reservas\ReservaSharpValidator::class,
            "authorizations" => [
                "delete" => false,
                "create" => false,
            ]
        ],
        "mensaje" => [
            "list" => \App\Sharp\Mensajes\MensajeSharpList::class,
            "form" => \App\Sharp\Mensajes\MensajeSharpForm::class,
           // "validator" => \App\Sharp\Reservas\ReservaSharpValidator::class,
            "authorizations" => [
                "delete" => false,
                "create" => false,
                "update" => false
            ]
        ]
    ],
    "menu" => [
        [
            "label" => "Usuarios",
            "icon" => "fa-users",
            "entity" => "user"
        ],
        [
            "label" => "Empresas",
            "icon" => "fa-building",
            "entity" => "empresa"
        ],
        [
            "label" => "Actividades",
            "entities" => [
                // [
                //     "label" => "Dashboard",
                //     "icon" => "fa-dashboard",
                //     "dashboard" => "company_dashboard"
                // ],
                [
                    "label" => "Actividades",
                    "icon" => "fa-space-shuttle",
                    "entity" => "actividad"
                ],
                [
                    "label" => "Categorías",
                    "icon" => "fa-space-shuttle",
                    "entity" => "categoria"
                ],
            ]
            ],
            [
                "label" => "Pagos",
                "icon" => "fa-credit-card",
                "entity" => "pago"
            ],
            [
                "label" => "Reservas",
                "icon" => "fa-wpforms",
                "entity" => "reserva"
            ],
            [
                "label" => "Mensajes",
                "icon" => "fa-envelope",
                "entity" => "mensaje"
            ],

    ],
    "uploads" => [
        "tmp_dir" => env("SHARP_UPLOADS_TMP_DIR", "tmp"),
        "thumbnails_dir" => "thumbnails",
    ],
    "extensions" => [
        "assets" => [
           "strategy" => "raw",
           "head"     => [
              "/css/main.css", // Outputs <link rel="stylesheet" href="/css/inject.css"> after sharp assets
           ],
        ],
        "activate_custom_form_fields" => true,
     ],
     "custom_url_segment" => "admin",
     "auth" => [
        "check_handler" => \App\Sharp\Auth\SharpCheckHandler::class,
        "guard" => "empresa"
     ],
     "display_sharp_version_in_title" => false,
];
```

**Comment by dvlpp** [comment]
Ah, I see, it might come from your custom guard. Why are you using a custom guard AND an auth check_handler?

I'm guessing it could be related to some old code that should be deleted in the way Sharp is handling custom guards. Could you try something quite unusual? Comment lines 71-77 of `Code16\Sharp\SharpServiceProvider`:

![image](https://user-images.githubusercontent.com/973325/56808060-e4ed8100-6830-11e9-885e-5ccc83870dd5.png)

And try again.

**Comment by rokkay** [comment]
I'll try It on Monday. We are using a custom guard because want to have difference between normal users and companies. 

The auth handler now i dont remember because using It, i'll check It.

**Comment by rokkay** [comment]
> 
> 
> Ah, I see, it might come from your custom guard. Why are you using a custom guard AND an auth check_handler?
> 
> I'm guessing it could be related to some old code that should be deleted in the way Sharp is handling custom guards. Could you try something quite unusual? Comment lines 71-77 of `Code16\Sharp\SharpServiceProvider`:
> 
> ![image](https://user-images.githubusercontent.com/973325/56808060-e4ed8100-6830-11e9-885e-5ccc83870dd5.png)
> 
> And try again.

This has not worked either. The same error occurs. This is the authentication handler:
```php
<?php

namespace App\Sharp\Auth;

use Code16\Sharp\Auth\SharpAuthenticationCheckHandler;

class SharpCheckHandler implements SharpAuthenticationCheckHandler{
    /**
     * @param $user
     * @return bool
     */
    public function check($user): bool
    {
        \Debugbar::info($user);
        return $user->hasAnyRole(['Administrador', 'Empresa']);
    }
}
```

**Comment by dvlpp** [comment]
Close because of inactivity — was unable to reproduce.
