### ISSUE TITLE
Invalid Handler for 2FA instance commands

### ISSUE THREAD

**Issue by IlyasDiker** [code16/sharp#493]
![image](https://github.com/code16/sharp/assets/28260951/c3388445-e9d4-4a36-acd9-433d578a071b)
![image](https://github.com/code16/sharp/assets/28260951/b2c3b914-c82b-4a81-9c0f-896527526ba4)

i have this issue happening to me for the both Activate2faCommand and Deactivate2faCommand

```php
<?php

namespace App\Sharp\Profile\Commands;

use Code16\Sharp\Auth\TwoFactor\Commands\Activate2faViaTotpWizardCommandTrait;
use Code16\Sharp\EntityList\Commands\Wizards\SingleInstanceWizardCommand;

class Activate2faCommand extends SingleInstanceWizardCommand
{
    use Activate2faViaTotpWizardCommandTrait;
}
``` 
in config
```
        '2fa' => [
            'enabled' => true,
            'handler' => 'totp',
        ],
```

logs: 
```
[2023-09-02 21:57:53] local.DEBUG: App\Sharp\Profile\Commands\Activate2faCommand  
[2023-09-02 21:57:53] local.ERROR: Handler for instance command [App\Sharp\Profile\Commands\Activate2faCommand] is invalid {"userId":1,"exception":"[object] (Code16\\Sharp\\Exceptions\\SharpException(code: 0): Handler for instance command [App\\Sharp\\Profile\\Commands\\Activate2faCommand] is invalid at C:\\Users\\Ilyas\\Desktop\\Git\\doocto-api\\vendor\\code16\\sharp\\src\\EntityList\\Traits\\HandleInstanceCommands.php:89)
[stacktrace]
#0 [internal function]: Code16\\Sharp\\Show\\SharpShow->Code16\\Sharp\\EntityList\\Traits\\{closure}('App\\\\Sharp\\\\Profi...', 1)
#1 C:\\Users\\Ilyas\\Desktop\\Git\\doocto-api\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Arr.php(558): array_map(Object(Closure), Array, Array)
#2 C:\\Users\\Ilyas\\Desktop\\Git\\doocto-api\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Collection.php(777): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#3 C:\\Users\\Ilyas\\Desktop\\Git\\doocto-api\\vendor\\code16\\sharp\\src\\EntityList\\Traits\\HandleInstanceCommands.php(79): Illuminate\\Support\\Collection->map(Object(Closure))
#4 [internal function]: Code16\\Sharp\\Show\\SharpShow->Code16\\Sharp\\EntityList\\Traits\\{closure}(Object(Illuminate\\Support\\Collection), 'instance')
#5 C:\\Users\\Ilyas\\Desktop\\Git\\doocto-api\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Arr.php(558): array_map(Object(Closure), Array, Array)
#6 C:\\Users\\Ilyas\\Desktop\\Git\\doocto-api\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Collection.php(777): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#7 C:\\Users\\Ilyas\\Desktop\\Git\\doocto-api\\vendor\\code16\\sharp\\src\\EntityList\\Traits\\HandleInstanceCommands.php(76): Illuminate\\Support\\Collection->map(Object(Closure))
#8 C:\\Users\\Ilyas\\Desktop\\Git\\doocto-api\\vendor\\code16\\sharp\\src\\EntityList\\Traits\\HandleInstanceCommands.php(24): Code16\\Sharp\\Show\\SharpShow->getInstanceCommandsHandlers()
#9 C:\\Users\\Ilyas\\Desktop\\Git\\doocto-api\\vendor\\code16\\sharp\\src\\Show\\SharpShow.php(75): Code16\\Sharp\\Show\\SharpShow->appendInstanceCommandsToConfig(Array, NULL)
#10 C:\\Users\\Ilyas\\Desktop\\Git\\doocto-api\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\helpers.php(307): Code16\\Sharp\\Show\\SharpShow->Code16\\Sharp\\Show\\{closure}(Array)
#11 C:\\Users\\Ilyas\\Desktop\\Git\\doocto-api\\vendor\\code16\\sharp\\src\\Show\\SharpShow.php(72): tap(Array, Object(Closure))
....
```

**Comment by IlyasDiker** [comment]
fixed, issue was from my side the class wasn't autoloaded correctly.
